# This is core test runner

image: maxking/mailman-ci-runner

variables:
  POSTGRES_DB: "mailman_test"
  POSTGRES_USER: "runner"
  POSTGRES_PASSWORD: "runner"
  MYSQL_ROOT_PASSWORD: "runner"
  MYSQL_USER: "runner"
  MYSQL_USER_PASSWORD: "runner"
  MYSQL_DATABASE: "test_mailman"
  LC_ALL: "C.UTF-8"

qa:
  script:
  - tox -e qa

docs:
  script:
  - tox -e docs

sqlite:
  script:
  - tox -e py35-nocov,py36-nocov

pgsql:
  services:
  - postgres:latest
  script:
  - MAILMAN_EXTRA_TESTING_CFG=/home/runner/configs/postgres.cfg tox -e py35-nocov-pg,py36-nocov-pg
  tags:
  - postgres

mysql:
  services:
  - mysql:latest
  script:
  - MAILMAN_EXTRA_TESTING_CFG=/home/runner/configs/mysql.cfg tox -e py35-nocov-mysql,py36-nocov-mysql
  tags:
  - mysql

diffcov:
  script:
  - tox -e py35-diffcov,py36-diffcov
  except:
  - master
