# This is core test runner

image: maxking/mailman-ci-runner

variables:
  POSTGRES_DB: "mailman_test"
  POSTGRES_USER: "runner"
  POSTGRES_PASSWORD: "runner"
  MYSQL_ROOT_PASSWORD: "runner"
  MYSQL_USER: "runner"
  MYSQL_USER_PASSWORD: "runner"
  MYSQL_DATABASE: "test_mailman"

qa:
  script:
  - tox -e qa

sqlite:
  script:
  - tox -e py34,py35

pgsql:
  services:
  - postgres:latest
  script:
  - MAILMAN_EXTRA_TESTING_CFG=/home/runner/configs/postgres.cfg tox -e {py34,py35}-pg
  tags:
  - postgres
